# Generated by Django 5.2.17 on 2026-10-02 16:08

import apps.market.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('capacity_quintal_per_day', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mill',
                'verbose_name_plural': 'Mills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_date', models.DateField()),
                ('moisture_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('broken_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grain_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('milling_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.market.models.lot_photo_upload)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='market.mill')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('quantity_wanted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_made', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='market.lot')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(choices=[('paddy', 'Paddy'), ('rice', 'Rice'), ('broken', 'Broken'), ('bran', 'Bran')], max_length=16)),
                ('grade', models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('common', 'Common')], default='common', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.market.models.variety_photo_upload)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_varieties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='market.lot')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='market.variety')),
            ],
            options={
                'verbose_name': 'Price Record',
                'verbose_name_plural': 'Price Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='market.variety'),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='market.variety')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'variety')},
            },
        ),
    ]
