# Generated by Django 5.2.17 on 2026-10-02 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='demand',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Demand in quintals', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='price_per_packet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per packet (₹ per 26 kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='quantity_packets',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packets (1 packet = 26 kg)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_made', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='market.lot')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negotiation',
                'verbose_name_plural': 'Negotiations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='market.lot')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['queue_position', 'created_at'],
                'unique_together': {('lot', 'buyer')},
            },
        ),
    ]
